baseURL = "https://www.catalystedge.org/"
languageCode = "en-us"
title = "Catalyst Edge"
theme = "clarity"
paginate = 10
enableRobotsTXT = true

[params]
  description = "Catalyst Edge empowers finance professionals with clarity, growth, and strategic wellbeing."
  favicon = "images/favicon.ico"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
